name: Create Release

on:
    push:
        branches:
            - master
            - OPS-3234-Create-Pipeline-for-new-release

jobs:
  release:
    runs-on: ubuntu-latest
    env:  
      GH_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}
      GH_PACKAGES_ACCESS_TOKEN_RW: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN_RW }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: |
          # Get latest tag or default to v0
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+$' | head -n1 || echo "v0")
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Create New Tag
        id: bump_version
        run: |
          old_tag="${{ steps.get_tag.outputs.tag }}"
          number=${old_tag#v}
          new_number=$((number + 1))
          new_tag="v$new_number"

          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        run: |
          git tag ${{ steps.bump_version.outputs.new_tag }}
          git push origin ${{ steps.bump_version.outputs.new_tag }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          release_name: Release ${{ steps.bump_version.outputs.new_tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
